### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#1]
There should be contributing guidelines for beginners to contribute to this project

**Comment by JavascriptDon** [comment]
Assign this to me!

**Comment by hasnainmakada-99** [comment]
> Assign this to me! 

Here you go

**Comment by JavascriptDon** [comment]
Please review my pull request!

**Comment by hasnainmakada-99** [comment]
Yes @JavascriptDon I'll review your pr after I return from my vacation, currently I'm traveling so my internet is fluctuating a lot. Sorry for the inconvenience
