### ISSUE TITLE
Add: Resources for Backend in Web Development

### ISSUE THREAD

**Issue by Vee339** [hasnainmakada-99/Open-Source-with-Hasnain#103]
I have just gone through the project and it is appreciable.

However, when I clicked on web development in resources, there were no links for backend technologies such as PHP and MySQL. 
![resources_sugg](https://user-images.githubusercontent.com/81091817/217540688-2185d133-c82a-48b1-acef-1dbdac5af077.png)

I will work on this issue but please provide me with the links to resources.

**Comment by hasnainmakada-99** [comment]
Yes @Vee339, I'll assign this issue to you but can you please specify which type of links of which resources do you want ? Means PHP, MySQL etc...

**Comment by Vee339** [comment]
I am thinking of PHP, Perl, Python, Node.js, MySQL, NoSQL, MongoDB, PostgreSQL, etc.

**Comment by hasnainmakada-99** [comment]
Yes @Vee339, you can proceed to add those resources

**Comment by Vee339** [comment]
@hasnainmakada-99 But which courses should I add? I mean, there are lots of free courses and also, I have knowledge of only PHP and MySQL.

**Comment by hasnainmakada-99** [comment]
In PHP and MySQL, you can explore freecodecamp they have a lot of courses on that tech stack. And if you like any of those courses, you can surely proceed to add that

**Comment by abhigyan631** [comment]
@hasnainmakada-99 Hi, I would like to add some resources to the "Machine learning resources" page. Actually, I am stuck in step 5 ('Create a new branch') and thus cannot proceed. Could you please help me proceed so I can go ahead and add them? Thanks in advance.

**Comment by hasnainmakada-99** [comment]
Hey @abhigyan631 , You can raise a new issue about adding resources and let us discuss your problem inside github discussions

**Comment by abhigyan631** [comment]
> Hey @abhigyan631 , You can raise a new issue about adding resources and let us discuss your problem inside github discussions

Thanks for the response, I just created the issue request.

**Comment by junaidahamed800** [comment]
@Vee339 Hi I am new to The open source contribution can i start contributing to this by adding Resources ?

**Comment by Vee339** [comment]
> @Vee339 Hi I am new to The open source contribution can i start contributing to this by adding Resources ?

Yes, you can. I also wanted to add but I didn't know which resources to add. If you know, you can definitely add.

**Comment by junaidahamed800** [comment]
I know the resources , but where and how do I add them?

**Comment by junaidahamed800** [comment]
@hasnainmakada-99 Hi i would like to add resources to this. How do i add them? I am new to this open source Contributions

**Comment by hasnainmakada-99** [comment]
Yes @junaidahamed800, our maintainer @edsodz is working on a guide on how to add resources, It will soon be uploaded to the site. Please stay tuned for a few days.

**Comment by ghost** [comment]
heya👋, @junaidahamed800 we just uploaded the guide on how to add resources. Please check the *how-to-add-resources.md* file. Let us know if you are facing any issues.

**Comment by junaidahamed800** [comment]
@edsodz sure, i will let you know if i have any issues

**Comment by hasnainmakada-99** [comment]
Any updates @junaidahamed800  and @Vee339 on this issue ?
