### ISSUE TITLE
Resources for Machine Learning

### ISSUE THREAD

**Issue by abhigyan631** [hasnainmakada-99/Open-Source-with-Hasnain#107]
Hi all, 
  I would like to go ahead and add some more resources in the Machine Learning page section. But I am stuck in step 5 ('Create a new branch') and thus cannot proceed. Could you please help me proceed so I can go ahead and add them? Thanks in advance.

**Comment by abhigyan631** [comment]
Is anyone here, please?

**Comment by hasnainmakada-99** [comment]
Yes @abhigyan631, sorry for the late reply. Can you please be more specific about what is happening with you when you try to add resources

**Comment by hasnainmakada-99** [comment]
@abhigyan631, You don't have to create a branch unless you're modifying the codebase, If you want to add resources, you can do that in your main branch of the forked repo and then raise a PR 😄. feel free to contact me

**Comment by abhigyan631** [comment]
Sorry for the late response, I will do it ASAP, thanks for the help

**Comment by hasnainmakada-99** [comment]
@abhigyan631, any updates on this issue ?

**Comment by abhigyan631** [comment]
> @abhigyan631, any updates on this issue ?

Is it possible that I share the links course links here instead of going through the process of GitHub please since I don't think that I can solve the issue?

**Comment by ghost** [comment]
Easy mode. You can do it @abhigyan631 . Check the *how-to-add-resources.md file*. PR the changes you made. If any modifications are required we will let you know. 🚀

**Comment by hasnainmakada-99** [comment]
@abhigyan631 

https://hasnainmakada-99.github.io/Open-Source-With-Hasnain/#/how-to-add-resources

**Comment by abhigyan631** [comment]
Sorry I will just share my article here for everyone's convenience, I just cant solve it, sorry to waste everyone's time

https://medium.com/datadriveninvestor/ivy-league-universities-machine-learning-free-courses-f17faa8355a9

**Comment by hasnainmakada-99** [comment]
No worries @abhigyan631, I'll assign this issue to someone else

**Comment by yugborana** [comment]
i would like to contribute

**Comment by yugborana** [comment]
@abhigyan631 would you please send the resources you collected? I would add them

**Comment by yugborana** [comment]
@hasnainmakada-99 please assign me

**Comment by hasnainmakada-99** [comment]
Here you go @yugborana

**Comment by yugborana** [comment]
i am adding the resources given by @abhigyan631 . Is it fine?

**Comment by hasnainmakada-99** [comment]
Yes, you can add that @yugborana

**Comment by yugborana** [comment]
ok thanks
