### ISSUE TITLE
Add more blockchain resources

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#115]
The directory structure for the resources.md file is as follows

[../pages/full-stack-blockchain-development.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/full-stack-blockchain-development.md)

**Comment by munnokd** [comment]
Can I add some more resources to this resources.md file?

**Comment by hasnainmakada-99** [comment]
Ya sure @munnokd, I am assigning this issue to you

**Comment by munnokd** [comment]
Okay I will add some more resources .

**Comment by yugborana** [comment]
i would like to contribute if @munnokd do not have any problem in assigning this to me @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
@munnokd is currently working on this issue @yugborana, If this issue remains in the staling period for a longer time then I'll assign it to you

**Comment by munnokd** [comment]
I added a pull request please review that pull request.
