### ISSUE TITLE
Add a detailed step-by-step procedure with the help of images

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#118]
**Is your feature request related to a problem? Please describe.**
The contributor should add images which explain more on how to add resources, In short, explain it visually

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
Here's the path to the file : https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/how-to-add-resources.md

**Comment by KendallDoesCoding** [comment]
What images must we add?

**Comment by hasnainmakada-99** [comment]
preview of how to md file should look after adding the resources @KendallDoesCoding

**Comment by karthiknadar1204** [comment]
i would like to wrk on this issue,could you please describe what has to done

**Comment by hasnainmakada-99** [comment]
See we just have to include a preview image inside the how-to guide to make the user understand how would the preview of the MD file will look after adding the resources, Like this 👇 @karthiknadar1204 and @KendallDoesCoding 
![image](https://user-images.githubusercontent.com/82728823/224503535-ba8c407a-5e48-4d9b-9573-dc84a2f4e553.png)

**Comment by KendallDoesCoding** [comment]
> See we just have to include a preview image inside the how-to guide to make the user understand how would the preview of the MD file will look after adding the resources, Like this 👇 @karthiknadar1204 and @KendallDoesCoding ![image](https://user-images.githubusercontent.com/82728823/224503535-ba8c407a-5e48-4d9b-9573-dc84a2f4e553.png)

Ok, If @karthiknadar1204 wants to work on this let them go ahead. If not, I will work on this.

**Comment by hasnainmakada-99** [comment]
@karthiknadar1204 do you want to work ?

**Comment by Sreekar-Shodhan** [comment]
@hasnainmakada-99 is this issue still open?

**Comment by Sreekar-Shodhan** [comment]
I mean if no one is still working on this then can I get this task assigned?

**Comment by karthiknadar1204** [comment]
@hasnainmakada-99 ,so sorry for the late response,i would like to work  it

**Comment by karthiknadar1204** [comment]
pleas assign this issue to me

**Comment by karthiknadar1204** [comment]
Will set up the project on my system and communicate further

**Comment by hasnainmakada-99** [comment]
Sure @karthiknadar1204

**Comment by karthiknadar1204** [comment]
Will begin the work this week and get back,was working on another issue so couldn't update you

**Comment by hasnainmakada-99** [comment]
> Will begin the work this week and get back,was working on another issue so couldn't update you
Not  a problem @karthiknadar1204

**Comment by karthiknadar1204** [comment]
@hasnainmakada-99 ,I had some issue while trying to set up the project in my system, cold you please guide me with how to resolve them
<img width="905" alt="Screenshot 2023-03-24 at 9 32 11 PM" src="https://user-images.githubusercontent.com/95973644/227579148-0aa77cdc-a848-4e92-93dd-d4fe4e6848a3.png">

**Comment by hasnainmakada-99** [comment]
Hey @karthiknadar1204, Sorry for the late reply, I would like to tell you that we accidentally pushed the `node_modules ` folder onto the main branch, now the issue has been solved

Steps to reproduce,

1. Delete the existing copy of the repository from your system
2. pull the new changes in the forked repo from the upstream branch
3. firstly run `npm i docsify -g `
4. Then install the docsify-cli by running `npm i docsify-cli -g`
5. And you're good to go.

If you again encounter any more issue feel free to tag me here

Sorry for the inconvenience caused 😞

**Comment by karthiknadar1204** [comment]
That really helps.
Will try setting up the project once again.
Thank you so much

**Comment by hasnainmakada-99** [comment]
Hey @karthiknadar1204 any updates on this issue ?

**Comment by karthiknadar1204** [comment]
Will share update tomorrow evening,is that fine?

**Comment by hasnainmakada-99** [comment]
Not at all a problem @karthiknadar1204

**Comment by karthiknadar1204** [comment]
@hasnainmakada-99 ,had a few discrepancies,will look over them during the weekend and keep you updated about it as well and merge a pr by monday evening,is that fine?

**Comment by hasnainmakada-99** [comment]
No problem @karthiknadar1204

**Comment by hasnainmakada-99** [comment]
Hey @karthiknadar1204, any updates ?

**Comment by karthiknadar1204** [comment]
@hasnainmakada-99 ,its my first time working with a project hosted on docker,i have set up the environment and got the project running on docker but cant seem to find a way to start the project on the browser,needed a little help.

Sorry for the late response.

**Comment by hasnainmakada-99** [comment]
Yes @karthiknadar1204, I understand but if you're gonna edit the files, then why did you pull the docker image ?, That docker image is just for hosting to different cloud services.

**Comment by karthiknadar1204** [comment]
Ohk,i did not know that to be honest...I was trying to follow the directions given in the repository to start running the project locally using docker

**Comment by karthiknadar1204** [comment]
I think i have the project running now,clicked on the link present in the docker,will go through the guidelines and share more soon

Thank you and sorry for the inconvenience and the delay

**Comment by karthiknadar1204** [comment]
I basically have to add a pictorial representation for the process being explained in how-to-add is that right @hasnainmakada-99

**Comment by karthiknadar1204** [comment]
@hasnainmakada-99 ,do you have any pics/jpg's that could be added for the visual explanation.

**Comment by hasnainmakada-99** [comment]
> I basically have to add a pictorial representation for the process being explained in how-to-add is that right @hasnainmakada-99 

Yes

**Comment by hasnainmakada-99** [comment]
> @hasnainmakada-99 ,do you have any pics/jpg's that could be added for the visual explanation.

I'll send you the pics by tomorrow @karthiknadar1204

**Comment by karthiknadar1204** [comment]
Fine @hasnainmakada-99

**Comment by karthiknadar1204** [comment]
@hasnainmakada-99 ,will try to wrap up the issue by day end,please share the pics

**Comment by hasnainmakada-99** [comment]
Here are the images @karthiknadar1204 ,

1. **Preview of the Markdown Code**
![image](https://user-images.githubusercontent.com/82728823/230334801-6d953267-5584-412d-b547-fe1aa07295a0.png)

2. **Preview of the markdown output**
![image](https://user-images.githubusercontent.com/82728823/230335275-9e277297-241b-40eb-8e92-4762ec0c08fd.png)

**Comment by hasnainmakada-99** [comment]
Hey @karthiknadar1204, are you done with this issue?
