### ISSUE TITLE
Add new resources inside android development.md

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#128]
The directory structure to the android resources file is as follows,

[./pages/android-development-resources.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/android-development-resources.md)

**Comment by SK-ILLish-GIT** [comment]
I am writing to request that I be assigned to add new resources to the android development.md file. I have a good knowledge in the field of Android app development and I am confident that I can provide quality resources to the file to help others in their development efforts.

**Comment by hasnainmakada-99** [comment]
And here you go @SK-ILLish-GIT

**Comment by hasnainmakada-99** [comment]
@SK-ILLish-GIT please do the changes as proposed in PR #129
