### ISSUE TITLE
Add resources for beginners in Web Development

### ISSUE THREAD

**Issue by ghost** [hasnainmakada-99/Open-Source-with-Hasnain#13]
The document hierarchy is as follows to add content If no web resources file is there then make sure to add a new one,

[./docs/pages](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/tree/main/docs/pages)

**Comment by 0xSaksham** [comment]
@edson-sooraj I can do this please assign me.

**Comment by ghost** [comment]
Go for it @0xSaksham

**Comment by hasnainmakada-99** [comment]
> @edson-sooraj I can do this please assign me.

Here you go

**Comment by SattyamSamania** [comment]
Hey @hasnainmakada-99 if the issue is still open I can work on this.

**Comment by hasnainmakada-99** [comment]
Yes @SattyamSamania, you can work on this

**Comment by hasnainmakada-99** [comment]
Sorry @SattyamSamania this issue has been assigned to @0xSaksham, but look for other issues too as we are constantly improving OSWH

**Comment by SattyamSamania** [comment]
@hasnainmakada-99 sure, no problem.

**Comment by hasnainmakada-99** [comment]
@0xSaksham  Are you still working on this pull request ?

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @hasnainmakada-99 for ideas

**Comment by SattyamSamania** [comment]
Hey @hasnainmakada-99 if no one is working,can I work on this issue?

**Comment by hasnainmakada-99** [comment]
@edsodz , Take the call

**Comment by hasnainmakada-99** [comment]
Hey @SattyamSamania I am assigning this issue to you

**Comment by SattyamSamania** [comment]
Hey @hasnainmakada-99 should I add in Web-development-resources.md file of create a new one. As this md file contains only one resource.

**Comment by hasnainmakada-99** [comment]
> Hey @hasnainmakada-99 should I add in Web-development-resources.md file of create a new one. As this md file contains only one resource.

No add resources in the existing md file
