### ISSUE TITLE
Separate file for contributors

### ISSUE THREAD

**Issue by yung-coder** [hasnainmakada-99/Open-Source-with-Hasnain#130]
### Separate file for contributors

**Describe the solution you'd like**
Currently the Contributors are listed in main Readme of the project which can we moved to separate  file for a a better Project Structure

**Comment by bajibpathan** [comment]
@yung-coder - I'm new to open source and would like to take-up this issue. Could you please assign this issue to me?
Thanks, 
Baji

**Comment by yung-coder** [comment]
Go ahead @bajibpathan  🚀

**Comment by bajibpathan** [comment]
@yung-coder  - Created the PR. Please review and advise if any changes needed. 
Thanks
