### ISSUE TITLE
Update: Changelog of this project

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#133]
#### The contributor can also use any third-party packages from NPM to update the changelog or they can manually write it

Path to the changeLog.md : https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/CHANGELOG.md

**Reach out to me for any further queries**

**Comment by at-the-vr** [comment]
Hey Hasnain, I saw your changelogs will be including commits after January 28th, can I have a go at this Issue ?

**Comment by hasnainmakada-99** [comment]
Hey @at-the-vr, Sorry for the late reply, You can proceed to solve this issue, I'll assign it to you

**Comment by hasnainmakada-99** [comment]
@at-the-vr. Have you started working on this issue ?

**Comment by at-the-vr** [comment]
Yeah, i was filtering those merges and bot related actions. Will let you know soon once its done
