### ISSUE TITLE
Add new resources inside DevOps 

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#134]
**Is your feature request related to a problem? Please describe.**
Contributors should add new resources inside DevOps

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
Path to the file: https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/devops-resources.md

**Comment by mhdamaan79** [comment]
Hi Hasnain, I would like to contribute and add some new resources inside DevOps

**Comment by Ishita-Ghosh-25** [comment]
Hi, Can I contribute to this Project?

**Comment by hasnainmakada-99** [comment]
Sorry @Ishita-Ghosh-25, @mhdamaan79 was first to comment on solving this issue, you can check out various issues on this repo or raise one.

**Comment by hasnainmakada-99** [comment]
and @mhdamaan79, I am assigning this issue to you
