### ISSUE TITLE
Design a complete new readme for this project

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#136]
**Is your feature request related to a problem? Please describe.**
**Hey everyone, I would like to request the contributors to design a complete new readme for this project, If you're not able to design it propose new changes which you would think will enhance the readme, but your contribution should make an impact.**

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
**Path to the readme file: [Readme.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/README.md)**

**Comment by Ayaan49** [comment]
I would like to suggest adding a "How to contribute" section in the README.md file.

**Comment by hasnainmakada-99** [comment]
@Ayaan49, It is already there

https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/Contributing.md

https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/how-to-add-resources.md

**Comment by ghost** [comment]
@hasnainmakada-99 i want to work on this . assign it to me & prove me your any social handle or discord id to ask questions related to it

**Comment by hasnainmakada-99** [comment]
Here you go @ankitrajrj

Here are my social handles

Showwcase:
 https://showwcase.com/hasnainmakada-99

Twitter:

https://twitter.com/Hasnain_Makada

**Comment by ghost** [comment]
@hasnainmakada-99  i have send you follow request with user id Ankitraj_rj17 on twitter . plz check ... i want to talk with you related to this topic

**Comment by hasnainmakada-99** [comment]
We can discuss this issue on discord @ankitrajrj

**Comment by hasnainmakada-99** [comment]
You can join our discord server

https://oswh.tech
