### ISSUE TITLE
Create new Issue templates for adding new resources for issue raisers

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#137]
**The contributor should add new issue creation templates, Whenever a user needs to add new resources, he/she should raise an issue first regarding which resource in which topic they would like to add.**

Reach out to me for any further queries 😄

**Comment by mhdamaan79** [comment]
👋 Hi Hasnain, I would like to contribute by adding an issue template for resource addition requests. The template will help streamline the process and gather essential information for evaluating and adding resources effectively. Here's a brief explanation of what the template would include:

- Issue Description: [Description of the resource and topic]
- Resource Details: [Type, Title/Name, Description, URL/Source]
- Topic or Category: [Specify the topic or category]
- Intended Audience: [Optional field for the intended audience]
- Benefits of Adding this Resource: [Explain the value and benefits]
- Additional Information: [Optional section for extra details]
- Checklist: [Optional checklist for completion]

**Comment by hasnainmakada-99** [comment]
Sounds good to me @mhdamaan79, I'm assigning it to you

**Comment by hasnainmakada-99** [comment]
Sounds good to me @mhdamaan79, I'm assigning it to you

**Comment by mhdamaan79** [comment]
I've raised a pull request (#140) to add a new Issue template for adding new resources for issue raisers. Please review the changes. Thank you! @hasnainmakada-99
