### ISSUE TITLE
add Discord icon & navigation bar, theme changer icon positioning

### ISSUE THREAD

**Issue by adisuyash** [hasnainmakada-99/Open-Source-with-Hasnain#144]
## Problems identified
1. The theme changer (dark to light) icon isn't placed properly on the web page. 
2. The Hamburger Menu icon also needs to be placed on the top-left corner of the webpage (for more users to access it easily).
3. Discord Icon needs to be placed in place of **Join our discord**

## Relevant Screenshot
![Screenshot 2023-05-25 091910](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/116362593/0f627f7d-c26e-4c2d-aa07-e5a6f38d2473)

**Comment by adisuyash** [comment]
I want to give it a try also

**Comment by hasnainmakada-99** [comment]
Yes @adisuyash, you can proceed to solve this issue

**Comment by adisuyash** [comment]
Thank You @hasnainmakada-99 
But I am still trying to run the project locally on my system.
I am on windows OS and getting this error

![image](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/116362593/6c4ae178-ce63-469f-a94e-62b47cff6976)

**Comment by hasnainmakada-99** [comment]
No worries @adisuyash, Delete the existing copy from your system and clone it again, 

After cloning, Just run
`npm i` and it will automatically install all the necessary dependencies

Notify me once you have done all the steps, smiley:

**Comment by hasnainmakada-99** [comment]
If you're getting the same error again,

Then please look into the official Docsify docs as well

https://docsify.js.org/#/quickstart

**Comment by adisuyash** [comment]
It is now running locally now just I have to figure out the files to modify

**Comment by hasnainmakada-99** [comment]
Okay then @adisuyash, reach out to me for any further queries

**Comment by adisuyash** [comment]
Reached you via discord

**Comment by hasnainmakada-99** [comment]
Hey @adisuyash, any updates on this issue

**Comment by adisuyash** [comment]
I am unable to locate the div tags because of the script used and it seems tougher to me
