### ISSUE TITLE
Add some new resources 

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#145]
I would like to request the contributor to add some new resources in any of the category which are there in this project.

Feel free to reach out in case of any queries 😀

**Comment by elidakirigo** [comment]
hello, i was going through eddiehub and found this issue and its a good first issue for me to start with, mind assigning me the issue?I'd like to contribute too.

**Comment by hasnainmakada-99** [comment]
Here you go @elidakirigo 🤠

**Comment by elidakirigo** [comment]
thanks. let me start working on it! @hasnainmakada-99

**Comment by Sakshikumari28** [comment]
hello @elidakirigo can I work in this project

**Comment by hasnainmakada-99** [comment]
Sure @Sakshikumari28, Please go ahead

**Comment by Sakshikumari28** [comment]
Is there any community channel which I can join.. As I'm new in the open source field..

**Comment by hasnainmakada-99** [comment]
Yes @Sakshikumari28, you join our discord channel for oswh

https://discord.gg/NReUHQD6EX

**Comment by hasnainmakada-99** [comment]
Hey @Sakshikumari28, any updates on this issue

**Comment by coderiksenthil** [comment]
I was scrolling through all repositories on GitHub I found this one simple to start with, if you can involve me in this project I can help you by contributing resources to this project and it will be also a learning point for me, please can you assign me to this project @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Sure sure @coderiksenthil, please go ahead contributing to this project, it will be a great help to us and don't forget to join our discord server 😊
