### ISSUE TITLE
Make sub categories of resources in the sidebar

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#146]
**Is your feature request related to a problem? Please describe.**
I would like to request the contributor to add some categories for resources which means that if the resource is of react and it comes under web development then inside web development it should have a separate category

Like this ⏩ /web-dev/react

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by elidakirigo** [comment]
hello, i was going through eddiehub and found this issue and its a good first issue for me to start with, mind assigning me the issue? i'll fork and check out the solution in the meantime.

**Comment by hasnainmakada-99** [comment]
No problem @elidakirigo, here you go


Feel free to reach out to me in case you have any queries

**Comment by elidakirigo** [comment]
sure   , let me start working on it! @hasnainmakada-99

**Comment by elidakirigo** [comment]
> /web-dev/react

hello, @hasnainmakada-99 kindly share the link to the web-dev/react .

**Comment by hasnainmakada-99** [comment]
> > /web-dev/react
> 
> hello, @hasnainmakada-99 kindly share the link to the web-dev/react .

So sorry for the late reply @elidakirigo, but can you please be more specific about what help do you want?

**Comment by elidakirigo** [comment]
> > > /web-dev/react
> > 
> > 
> > hello, @hasnainmakada-99 kindly share the link to the web-dev/react .
> 
> So sorry for the late reply @elidakirigo, but can you please be more specific about what help do you want?

on the first comment above, i noticed you have said you need the web developement to have a separate category

Like this ⏩ /web-dev/react - where can i find the '/web-dev/react' ?

**Comment by hasnainmakada-99** [comment]
Ohh, That category you have to create it @elidakirigo, and then filter out the resources according to the category

**Comment by elidakirigo** [comment]
> Ohh, That category you have to create it @elidakirigo, and then filter out the resources according to the category

okay. thankyou

**Comment by elidakirigo** [comment]
hi @hasnainmakada-99, I hope you're doing well

- kindly explain my two questions here.

- do you mean creating folders and arranging them, 
- or will it be restructuring the tables of the markdown files

thanks.
regards.

**Comment by hasnainmakada-99** [comment]
Hey @elidakirigo, Here's the complete breakdown of what you have to do in this issue

* Firstly you have to create a new file inside the `./pages` directory inside which you have to put the name of the tech stack of which you are providing the resources, for example, `./pages/react-resources.md` and after then, go to the existing set of resources inside the `./pages/web-development-resources.md` file, and pick the resources which belong to the particular tech stack of which you've created the resource file for it, and this similar thing goes to other resources of different tech stacks too.


And don't forget to structure the tables, if you don't know how to, check out the [how to add resources guide](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/how-to-add-resources.md)

I hope this answer your query, feel free to reach me out for any further doubts too 😄

**Comment by elidakirigo** [comment]
thankyou @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Hey @elidakirigo, Any updates on this issue ?

**Comment by elidakirigo** [comment]
hey, sorry I got held up, I'll update you tomorrow. @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
No worries @elidakirigo

**Comment by elidakirigo** [comment]
hi @hasnainmakada-99 I'd like to request for help as i got stuck

**Comment by hasnainmakada-99** [comment]
Now worries @elidakirigo, you can come to the discord server, let's sort your issue out

**Comment by elidakirigo** [comment]
hi, @hasnainmakada-99 will I need to update the `_layout/sidebar.md` too?

**Comment by hasnainmakada-99** [comment]
Yes @elidakirigo
