### ISSUE TITLE
The server is down

### ISSUE THREAD

**Issue by Bashamega** [hasnainmakada-99/Open-Source-with-Hasnain#149]
**Describe the bug**
I tried to visit the website from the link [down in the about](https://oswh.tech/). And it gave me simply a blank page and set the title to the title of the repo
**To Reproduce**
I don't know. I guess fix the hosting
**Expected behavior**
It should open the website
**Screenshots**
![image](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/110662505/1883f5cf-18b9-4507-aba9-a64960dbc935)

**Comment by hasnainmakada-99** [comment]
@Bashamega, 

It's working correctly on my end, please try it once again
![image](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/82728823/a7bb11e1-51da-446d-bfc3-cb08e98d2290)

**Comment by Bashamega** [comment]
> @Bashamega,
> 
> It's working correctly on my end, please try it once again ![image](https://user-images.githubusercontent.com/82728823/246757795-a7bb11e1-51da-446d-bfc3-cb08e98d2290.png)

It is not working.
I am in Egypt. Do you think this is the bug.
But I use the internet with VPN all the time here.

**Comment by hasnainmakada-99** [comment]
> > @Bashamega,
> > It's working correctly on my end, please try it once again ![image](https://user-images.githubusercontent.com/82728823/246757795-a7bb11e1-51da-446d-bfc3-cb08e98d2290.png)
> 
> It is not working. I am in Egypt. Do you think this is the bug. But I use the internet with VPN all the time here.

Let me check with the hosting as this project is hosted on GitHub so I don't think that there should be any errors, but then also I'll see

**Comment by Bashamega** [comment]
> > > @Bashamega,
> > > It's working correctly on my end, please try it once again ![image](https://user-images.githubusercontent.com/82728823/246757795-a7bb11e1-51da-446d-bfc3-cb08e98d2290.png)
> > 
> > 
> > It is not working. I am in Egypt. Do you think this is the bug. But I use the internet with VPN all the time here.
> 
> Let me check with the hosting as this project is hosted on GitHub so I don't think that there should be any errors, but then also I'll see
Ok. Take your time
if this website has a github link I can try that.

**Comment by hasnainmakada-99** [comment]
Hey @Bashamega, I've tried out with several VPNs and tested this project in different regions but it was working fine as I expected, It may happen on your end as GitHub sometimes have issues so we can not figure out whats happening, but its all working now
