### ISSUE TITLE
[Update] - Migrating to React

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#153]
This project is going to be migrated to the React Ecosystem and we're looking for folks who could help us achieve that goal

Feel free to reach me out for further queries

**Comment by aarpardev** [comment]
Hi, @hasnainmakada-99 

I'm interested in assisting you with this project. Can you elaborate with some extra details in terms of what you want with the project? Are you building a full-stack system with a back-end for contributors and editors? Do you need the same visual layout / CSS specs on the front-end but modular to speed things up? What extra features do you need?

- Aaron

**Comment by hasnainmakada-99** [comment]
> Hi, @hasnainmakada-99
> 
> I'm interested in assisting you with this project. Can you elaborate with some extra details in terms of what you want with the project? Are you building a full-stack system with a back-end for contributors and editors? Do you need the same visual layout / CSS specs on the front-end but modular to speed things up? What extra features do you need?
> 
> * Aaron

Hey @aarpardev thanks for taking up this issue, Can I get back to you by tomorrow 12:00 PM IST as I have been caught up with some work

**Comment by hasnainmakada-99** [comment]
Hey @aarpardev, You can join our discord where my teammates will you help you break down this issue more

here's the link to join: https://discord.gg/d3uzRXFG9h

**Comment by mirsahib** [comment]
hey @hasnainmakada-99 i would like to help if you need extra hand on this issue

**Comment by hasnainmakada-99** [comment]
We are in big need of helping hands @mirsahib , please join our discord server

**Comment by hasnainmakada-99** [comment]
> Hey @aarpardev, You can join our discord where my teammates will you help you break down this issue more
> 
> here's the link to join: https://discord.gg/d3uzRXFG9h

.

**Comment by ujju2000** [comment]
Hi @hasnainmakada-99, i would also like to help and contribute to this project.

**Comment by hasnainmakada-99** [comment]
Hey @ujju2000, join our discord server, I am going to close this issue now so we'll communicate over there itself
