### ISSUE TITLE
theme change bug

### ISSUE THREAD

**Issue by Abhishek-Panwar-2004** [hasnainmakada-99/Open-Source-with-Hasnain#163]
When the user scroll down and dark mode button comes adjacent to the github button, the dark mode button redirects to the github. 

This is happening because the dark mode button comes inside the github icon <div>

![image](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/127662041/fe243ee7-4847-4805-9e18-10bb110cf470)

**Comment by hasnainmakada-99** [comment]
Hey @Abhishek-Panwar-2004, thanks for addressing this issue, will you help us solve this one?

**Comment by Abhishek-Panwar-2004** [comment]
@hasnainmakada-99  yeah sure, thanks for giving me this opportunity.

**Comment by hasnainmakada-99** [comment]
Alright, I'm assigning this to you 😄

**Comment by Abhishek-Panwar-2004** [comment]
Hey, I am having problem running this project locally. Please help.

**Comment by hasnainmakada-99** [comment]
Hey @Abhishek-Panwar-2004, you can check out the official docsify docs 👇🏻

https://docsify.js.org/#/quickstart?id=quick-start

**Comment by Abhishek-Panwar-2004** [comment]
I am searching for the html file to change logo position but i couldn't find any file related to it. Am I missing something?

**Comment by hasnainmakada-99** [comment]
> I am searching for the html file to change logo position but i couldn't find any file related to it. Am I missing something?

Hey @Abhishek-Panwar-2004, you have to look at the readme.md file of this project since this project is based on docsify, The readme.md file is the landing page of this project

**Comment by Abhishek-Panwar-2004** [comment]
Please review my pull request.

**Comment by hasnainmakada-99** [comment]
@Abhishek-Panwar-2004, Raise A new PR

**Comment by hasnainmakada-99** [comment]
@Abhishek-Panwar-2004 Any updates on this issue?

**Comment by Abhishek-Panwar-2004** [comment]
@hasnainmakada-99 in progress

**Comment by hasnainmakada-99** [comment]
No worries @Abhishek-Panwar-2004

**Comment by hasnainmakada-99** [comment]
Hey @Abhishek-Panwar-2004, Any updates on this issue?

**Comment by hasnainmakada-99** [comment]
Hey @Abhishek-Panwar-2004, I am unassigning you from this issue as It's been on stale mode from the last 2 months

This issue is now open for everyone

**Comment by shreyansh1410** [comment]
Hey, @hasnainmakada-99 I would like to work on this issue, but I'm a beginner so I might need some help

**Comment by hasnainmakada-99** [comment]
Hey @shreyansh1410, You can proceed to solve this one

Here's a quick reference of what this issue is about

https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/issues/163#issue-1848657423

**Comment by abhiraj-ku** [comment]
Hey @hasnainmakada-99 I want to work on this issue. I can fix this

**Comment by hasnainmakada-99** [comment]
Hey @abhiraj-ku, so sorry but this issue has been assigned to @shreyansh1410, you can check out other issues or raise any if you have

If this issue stays stale for a long time, then I'll surely assign it to you

**Comment by shreyansh1410** [comment]
@hasnainmakada-99 I have created a PR, please review :)

**Comment by shreyansh1410** [comment]
#191

**Comment by hasnainmakada-99** [comment]
Will review it by the end of this week @shreyansh1410
