### ISSUE TITLE
Convert all the resoruces into a JSON file

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#164]
I would like to request the contributor to provide any solutions on how to convert the markdown tables into JSON format like structure something like `resources.json` inside which we are having all the resources in our JSON format

We are going to switch to the react ecosystem soon, so the integration of MongoDB will require JSON format

Any solutions are welcome here

**Comment by Arindam200** [comment]
I would love to contribute!

**Comment by LalitAswal** [comment]
this might help 
https://www.npmjs.com/package/markdown-tables-to-json

**Comment by hasnainmakada-99** [comment]
Hey @Arindam200, Let's Do this, I am assigning this issue to you 💯

**Comment by hasnainmakada-99** [comment]
> this might help https://www.npmjs.com/package/markdown-tables-to-json

Thanks for sharing this @LalitAswal, will definitely have a look on this 😄

**Comment by hasnainmakada-99** [comment]
@Arindam200, any updates on this issue?

**Comment by Arindam200** [comment]
Hey @hasnainmakada-99 ! 

Due to my bad health, I wasn't able to work on this. Now I'll start working on this.

**Comment by hasnainmakada-99** [comment]
No worries @Arindam200, It's completely fine

**Comment by hasnainmakada-99** [comment]
Hey @Arindam200, I am unassigning this issue to you as it was in the stale period for pretty much long time and yeah I am opening it for hacktoberfest

**Comment by SahilSinghTomar** [comment]
hello, can I can work on this issue  ??

**Comment by SahilSinghTomar** [comment]
I can work on the issue. Can u please assign me ?

**Comment by hasnainmakada-99** [comment]
Sure @SahilSinghTomar
