### ISSUE TITLE
[Add]: Guide on how to run this project locally on host machine

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#166]
**Describe the bug**
There is a Requirement to add a guide on how to run this project locally on machine, So I would like to request to the contributor that they should add the guide inside this project

**To Reproduce**
None

**Expected behavior**
None

**Screenshots**
None

**Additional context**
None

**Comment by Madhurchandran** [comment]
first : git clone of the repository which you wanted to run in your local machine then install the dependencies, then update the configurations.
**Reference**
1. https://www.neonscience.org/resources/learning-hub/tutorials/github-git-clone (Detail visualize overview)
2. https://dev.to/ceceliacreates/how-to-run-a-project-from-github-locally-30d1

**Comment by hasnainmakada-99** [comment]
Thanks for providing us with some resources @Madhurchandran, But actually we are seeking someone who could write the guide in a markdown file for us 😄

**Comment by Madhurchandran** [comment]
I want to try this can you explain it, hint.

**Comment by hasnainmakada-99** [comment]
> I want to try this can you explain it, hint.

Sure @Madhurchandran, This project is based on [docsify](https://docsify.js.org/#/), so now you have to write out a guide in markdown language with good design on how new contributors can run this project in their machine, basically set up the project in their machine

If you have any more queries, feel free to reach me here 😄

**Comment by Madhurchandran** [comment]
@hasnainmakada-99 what you want new file about version control, in this project can you give me more detail what should write prequisites any programming language requirenment, i want to try this.

**Comment by hasnainmakada-99** [comment]
No @Madhurchandran, I am saying like to add a guide like a readme file specifically targeting first-time users, so that whoever any new contributor comes to this project, they can run the project inside their local machine by just following the guide

For example, have a look at this guide of link free 👇🏻 
https://linkfree.io/docs/quickstart-json

**Comment by Madhurchandran** [comment]
@hasnainmakada-99  you already have file contributing.md so you want changes in that file or new file

**Comment by hasnainmakada-99** [comment]
A new File @Madhurchandran
