### ISSUE TITLE
[Idea]: Suggest some further improvments for this project

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#172]

**Comment by SahilSinghTomar** [comment]
You can add roadmaps for to learn some skills downloaded from roadmap.sh

**Comment by GaneshSharma8** [comment]
You can add some resources for SQL, ORMs, and server side caching for backend development.

**Comment by hasnainmakada-99** [comment]
The ideas are great @SahilSinghTomar and @GaneshSharma8, We can definitely add them, I'll look into it and raise further issues regarding adding the resources 😄

**Comment by ishitarakchhit** [comment]
We can add more resources into CSS section of your website. There are currently 5 resources but we can add few games like frontendmentor, frog jump, etc. which help new learners to learn CSS effectively and in a fun way. I will really appreciate if your open this as an issue.

**Comment by hasnainmakada-99** [comment]
Sounds good @ishitarakchhit

**Comment by Gyanendra-Verma** [comment]
I want to contribute , kindly assign this to me @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Sure @Gyanendra-Verma, you can go ahead to solve this issue

**Comment by Gyanendra-Verma** [comment]
This is my first open source contribution, kindly provide me with what have to do @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Actually this issue is all about implementing the ideas the contributor has regarding this project, so you have to suggest improvements related to this project @Gyanendra-Verma

**Comment by hasnainmakada-99** [comment]
Closing this issue as we have gathered pretty good ideas and now it's time to start the implementing them
