### ISSUE TITLE
Add more and more DevOps workflows to improve the project

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#173]
**Is your feature request related to a problem? Please describe.**
I would like to request the contributor to add more devops CICD workflows which can improve the health of the existing project

**Describe the solution you'd like**
NaN

**Describe alternatives you've considered**
NaN

**Additional context**
To learn more about the tools, Check out https://landscape.cncf.io/

**Comment by ptiwari6239** [comment]
Hi,
I'd like to work on this issue. Could you please assign it to me?
What's the specific problem we're addressing here, and do you have any initial thoughts on potential solutions?
Thanks,

**Comment by hasnainmakada-99** [comment]
> Hi, I'd like to work on this issue. Could you please assign it to me? What's the specific problem we're addressing here, and do you have any initial thoughts on potential solutions? Thanks,

Yes @ptiwari6239, The idea is to automate certain tasks such as

- Releasing new releases when any major changes are there
- automatic labels assigner
- bots
- and many more ideas which you can think that will improve this project

**Comment by ptiwari6239** [comment]
OK, as a beginner I would like to try. Can you please assign it to me? 
I can create a Jenkins pipeline for the same

**Comment by hasnainmakada-99** [comment]
Here you go @ptiwari6239

**Comment by hasnainmakada-99** [comment]
Closing this issue for being stale for a pretty long time @ptiwari6239, let me know if you want to resolve it
