### ISSUE TITLE
Design the Resources page of this project

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#175]
**Is your feature request related to a problem? Please describe.**
I would like to request the contributors, if you're from Ui/Ux, then helping us design a resource page will be of great help, the resources page will be used to show the users the resources which are uploaded by other contributors.

**Describe the solution you'd like**
You can design the landing page in Figma, photoshop or any software of your choice, but if possible try to do it in figma

**Describe alternatives you've considered**
NaN

**Additional context**
You can reach out to the maintainers on twitter: https://x.com/Hasnain_Makada

You can provide the design in any format of your choice 😄

**Comment by arun-h** [comment]
hey Hasnain,

Thank you for sharing the opportunity to contribute to the design of the Resources page (#175). I'm excited about the prospect of working on this and I'm happy to take up the challenge.

I'll begin by delving into the project's context and requirements. Could you provide more details on the types of resources to be showcased and any specific design elements or themes to consider?

please share any preferences or guidelines you have in mind.

**Comment by ratishjain12** [comment]
Hey @hasnainmakada-99 I am seeing you are currently using tables to show resources, I suggest implementing cards in a grid for the resources.

Do tell me what do you think about it, if it works I can work on it :)

**Comment by nishantshukla2884** [comment]
i am interested , please assign it to me @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Hey @arun-h, I am assigning this issue to you, Thanks for showing your interest

**Comment by hasnainmakada-99** [comment]
The Resources are already there, you can check it out on https://oswh.tech @arun-h

**Comment by hasnainmakada-99** [comment]
Hey @nishantshukla2884, Are you up for solving this issue?

**Comment by Shivansh230367** [comment]
Hey @hasnainmakada-99 , I am interested .Please assign it to me.

**Comment by hasnainmakada-99** [comment]
Yes @Shivansh230367 I am assigning this issue to you

**Comment by Gyanendra-Verma** [comment]
i want to contribute , kindly assign this to me @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Sorry @Gyanendra-Verma but @Shivansh230367 has already been assigned to this issue

**Comment by Shivansh230367** [comment]
Please give me some information regarding what exactly i have to design the resource page.
@hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Hey @Shivansh230367, You have to design the Resources page using any tools like figma or canva you can see the current page of how the resources are presented currently inside the project, and based on your design the design will be implemented in code and then publish to the end website

**Comment by Shivansh230367** [comment]
Where can i see the current page of how the resources are presented currently in this project.
@hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
> Where can i see the current page of how the resources are presented currently in this project. @hasnainmakada-99

checkout https://oswh.tech

**Comment by Shivansh230367** [comment]
https://www.figma.com/file/F57jOvdyE2z5HEtHukYAQA/github1?type=design&node-id=0%3A1&mode=design&t=2GNmWlHQyPtUcQh0-1

**Comment by Shivansh230367** [comment]
@hasnainmakada-99  above is a prototype of resource page.
Do tell me if i could make a pull request.

**Comment by hasnainmakada-99** [comment]
Hey @Shivansh230367, this was not the resources page, this is the landing page of the main website 😅,

The resources page is here 

https://oswh.tech/#/pages/devops-resources


Similarly you can navigate further from the sidebar as well

**Comment by Shivansh230367** [comment]
So can you just open a new issue for resource page also.
It will be great as i will get 2 of my successfull pull request and time is also running out, additionally i am a beginner.
So please do the needfull.
@hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Sorry @Shivansh230367 but we cannot break the rules just because you want to complete PRs for hacktoberfest, the main goal is to have fun while contributing to open source, not just to merge Pr's and if ou are going to solve this issue, mention this issue number inside your PR and we'll review it and give you instant feedback

**Comment by hasnainmakada-99** [comment]
Closing this issue as it is solved by @Akshaya101 now
