### ISSUE TITLE
[Redesign]: A new look to the Readme

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#180]
**Is your feature request related to a problem? Please describe.**
The whole project needs a new lookup of readme, And keep in mind that the main `readme.md` file is the homepage of the website so try to make the readme more appealing to the end user

**Describe the solution you'd like**
NaN

**Describe alternatives you've considered**
NaN

**Additional context**
NaN

**Comment by Illuminati9** [comment]
Hey @hasnainmakada-99 , I would like to work on this issue. Can you explain the issue clearly??

**Comment by MeMeee1** [comment]
**Is your feature request related to a problem? Please describe**.
I've identified an opportunity to enhance the project's documentation and user experience. Currently, the README lacks a dedicated FAQ section, which can help address common user queries, and it lacks a structured resource listing, making it harder for users to access curated materials.

Describe the solution you'd like
I would like to propose the addition of two essential sections to our project's README:

FAQ Section: This will provide answers to frequently asked questions related to using the resources and contributing to the project. It will make it easier for users to find solutions to common queries.
Resource Listing: To enhance user accessibility, I'd like to include a well-organized list of curated resources within specific categories (e.g., Learning Materials, Contribution Guides, Useful Tools). This will help users quickly discover the materials they need.

_**Describe alternatives you've considered**_
I've considered the status quo, where the README lacks these features, and it might lead to users having difficulty finding information or solutions. By adding these sections, I aim to improve user satisfaction and engagement.

Additional context
NaN

I'm interested in working on this issue; please assign it to me

**Comment by hasnainmakada-99** [comment]
Your ideas look quite promising to me @MeMeee1, Let's do it 🔥

**Comment by Shivansh230367** [comment]
Hey, @hasnainmakada-99 , I would like to work on this issue.
Please give me a chance to contribute.

**Comment by hasnainmakada-99** [comment]
I am sorry @Shivansh230367 but @MeMeee1 has already been assigned to this issue

**Comment by hasnainmakada-99** [comment]
@MeMeee1 any updates on this issue?

**Comment by hasnainmakada-99** [comment]
@MeMeee1, I am assigning this issue to someone else, as you are not giving any updates regarding this issue

**Comment by hasnainmakada-99** [comment]
Everyone, This issue is up for solving

**Comment by vaibhavkumawat-17** [comment]
hey @hasnainmakada-99 I would love to work on this issue,
Please give me a chance to contribute.

**Comment by vaibhavkumawat-17** [comment]
I have some ideas to enhance the banner image

**Comment by OfficialChrisTucker** [comment]
i am down

**Comment by hasnainmakada-99** [comment]
> I have some ideas to enhance the banner image

Yeah sure @vaibhavkumawat-17 please go ahead and solve this issue 😊

**Comment by hasnainmakada-99** [comment]
Closing this issue as it is in Stale period for a pretty long time
