### ISSUE TITLE
When sidebar collapses, the HTML, CSS and React Resource pages do not align properly.

### ISSUE THREAD

**Issue by replyre** [hasnainmakada-99/Open-Source-with-Hasnain#182]
Here is a screenshot of the issue, I found while visiting the site.

![Screenshot (213)](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/121796450/9f55869d-bdae-4268-8322-3a6d26ac8ac8)

It should appear like this:

![Screenshot (214)](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/121796450/e6985d95-a5d9-46db-a90e-6c6114f07c8a)

**Comment by hasnainmakada-99** [comment]
Yes @replyre, I am opening this issue and labeling it as a part of hacktoberfest and good first issue 😄
