### ISSUE TITLE
Alignment of navbar in mobile viewport and overlapping of theme toggle button with tables.

### ISSUE THREAD

**Issue by Avilash-Saha** [hasnainmakada-99/Open-Source-with-Hasnain#187]
**Describe the bug**
1. A part of the navbar goes behind the GitHub link when viewed in mobile viewport
2. The Dark & light theme toggle button overlaps with the tables.

**To Reproduce**
1. View the webpage in mobile viewport

**Expected behavior**
1.The whole navbar should be properly visible in the mobile viewport.
2.The theme toggle button should not overlap with the tables.

**Screenshots**
![open2](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/85384757/44b8b474-89a7-4a7e-9075-f9be1e954afe)
![open](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/85384757/64a1301e-9de6-4cb4-bea1-d6d68f754923)

Please allow me to work on this issue under hacktoberfest23.

**Comment by hasnainmakada-99** [comment]
Sure @Avilash-Saha Please proceed, I am assigning this issue to you
