### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#19]
Issue templates are needed to report bugs, add a new feature, etc..

For your reference: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by yung-coder** [comment]
Hey @hasnainmakada-99 i would like help out with it ...

**Comment by hasnainmakada-99** [comment]
Here you go @yung-coder
