### ISSUE TITLE
Adding a new resource.

### ISSUE THREAD

**Issue by arushitrivedi** [hasnainmakada-99/Open-Source-with-Hasnain#193]
**Issue Description**
I wanted to add a very useful and handy resource for newbies who have started their journey in development.
**Resource Details**
**Resource Type:** Website
**Title/Name of the Resource:** [Devdocs]
**Description:** [DevDocs is an online platform and documentation aggregator that provides a centralized place for software developers to access documentation for a wide range of programming languages, libraries, frameworks, and tools.]  
**URL or Source:** [https://devdocs.io/]

**Topic or Category**
Web Development

**Intended Audience (optional)**
Beginners

**Benefits of Adding this Resource**
DevDocs offers a searchable interface that allows developers to quickly find and access documentation for various technologies without having to visit multiple websites or documentation sources. It includes documentation for popular programming languages like JavaScript, Python, Ruby, and many others, as well as documentation for frontend and backend frameworks, libraries, and APIs.

**Additional Information (optional)**
It's a handy resource for developers who often need to reference documentation while coding or troubleshooting issues.
![devdocs](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/76534621/3332a09c-640d-4225-9099-28088272cb00)

**Checklist (optional)**
- [ x] I have conducted a search to ensure this resource is not a duplicate.
- [ x] I confirm that this resource complies with the guidelines and policies of the project/repository.

**Comment by hasnainmakada-99** [comment]
Hey @arushitrivedi, Yes you can surely go ahead and proceed to solve this issue, but please keep in mind that we are not labelling the resource additions as hacktoberfest issues, So if you contribute to us on the code side, you can raise new issues

**Comment by nishantshukla2884** [comment]
i am interested , kindly assign this to me @hasnainmakada-99

**Comment by nishantshukla2884** [comment]
@arushitrivedi  can i also co contribute with you

**Comment by hasnainmakada-99** [comment]
Sorry @nishantshukla2884, but @arushitrivedi has already been assigned to this issue, You can look out for other issues in the project
