### ISSUE TITLE
[Design]: Implement collapsible button in navbar

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#195]
**Describe the bug**
I would like to request the contributor to implement a collapsible button in the web development section

**To Reproduce**
NaN

**Expected behavior**
![image](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/82728823/c66bf34f-8096-4031-affd-b761050949bc)

**Screenshots**
The current situation is like this

![image](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/82728823/351c85bb-0da6-4198-8ce3-54edbb38a0e3)

**Additional context**
NaN

**Comment by naikmubashir** [comment]
Assign me this issue, I would like to solve it.

**Comment by hasnainmakada-99** [comment]
Hey @naikmubashir, You should have first waited to let me assign this issue to you and not just directly raise the PR, this is not a good practice

**Comment by naikmubashir** [comment]
I'm just a beginner and I will keep that in mind for the next time.
So I close the PR and let you assign the issue first?

**Comment by hasnainmakada-99** [comment]
Yes @naikmubashir

**Comment by Dedsec0098** [comment]
Hey @hasnainmakada-99 can you please assign me as a contributor to fix this issue.
Also do I need to include all the content from HTML resources to Backend Development resources inside the collapsible button?

**Comment by SanyaArora123** [comment]
hey @hasnainmakada-99 can you please assign this issue to me .

**Comment by hasnainmakada-99** [comment]
I am sorry @SanyaArora123  and @Dedsec0098 , but @naikmubashir was the first to help on this issue, so the issues will be assigned on a first come first serve basis
