### ISSUE TITLE
Button to open sidebar is showing in bottom  of the page

### ISSUE THREAD

**Issue by basavarajakj** [hasnainmakada-99/Open-Source-with-Hasnain#197]
**Describe the bug**
Could you please notice button to open sidebar is showing in bottom its not good in small screen devices

**To Reproduce**
Go to home page u can notice.

**Expected behavior**
Button should be in navbar for small screen devices.

**Screenshots**
![image](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/97227305/36e429d9-d43e-478d-8d71-5921c4dbf039)

**Additional context**
I would like contribute on this please assign to me

**Comment by basavarajakj** [comment]
!assign

**Comment by hasnainmakada-99** [comment]
Hey @Basavarajakjbasuu, Thanks for raising this bug, You can go ahead to solve this I am assigning this to you

**Comment by basavarajakj** [comment]
@hasnainmakada-99  For these style where CSS file are there and where is html codes

**Comment by naikmubashir** [comment]
Assign me this issue.

**Comment by hasnainmakada-99** [comment]
> @hasnainmakada-99 For these style where CSS file are there and where is html codes

Actually, this project is based on docsify @Basavarajakjbasuu. so you can find the HTML and CSS files on the root directory of this project

**Comment by basavarajakj** [comment]
Could you please tell root directory folder name😅

**Comment by hasnainmakada-99** [comment]
You can search for index.html and for CSS resources , check out the styles directory @Basavarajakjbasuu

**Comment by shreyansh1410** [comment]
Hey @hasnainmakada-99, check this out: [fixed issue #197](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/pull/205#issue-1945248344)

**Comment by shreyansh1410** [comment]
can you assign this issue to me?

**Comment by basavarajakj** [comment]
I have gone through ```docsify ``` documentation its a default behavior's  and Its quite tricky to make and even If we hardcode also It will affect to other functionality.  

```docsify``` abstract the html and css pages 

![image](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/97227305/d1049882-efcb-420b-b3fa-6711bd2e0d84)

If you have any suggestion could you please share

**Comment by hasnainmakada-99** [comment]
> I have gone through `docsify ` documentation its a default behavior's and Its quite tricky to make and even If we hardcode also It will affect to other functionality.
> 
> `docsify` abstract the html and css pages
> 
> ![image](https://user-images.githubusercontent.com/97227305/276179133-d1049882-efcb-420b-b3fa-6711bd2e0d84.png)
> 
> If you have any suggestion could you please share

Then if docsify doesn't allow us to modify the components, then let's close this issue @basavarajakj
