### ISSUE TITLE
[update]: OSWH ChangeLog updation (Automation)

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#200]
**Is your feature request related to a problem? Please describe.**
I would like to request the contributor that the changelog should automatically get updated to it's latest version after a certain amount of commits have been made to the project, similar to what big scale projects do, such as biodrop etc..

**Describe the solution you'd like**
I am completely clueless of how to do this, so seeking help of the community

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by SahilSinghTomar** [comment]
I can try to solve this issue. Can u assign it to me ??

**Comment by hasnainmakada-99** [comment]
Here you go @SahilSinghTomar

**Comment by SahilSinghTomar** [comment]
Thank you! I will on this issue right now. I was busy these past 3 days.

**Comment by SahilSinghTomar** [comment]
I guess we have to start using Conventional Commits.
for examples : -
- fix: resolve some errors.
- feat: new feature introduced

For your reference read this article - 
https://www.conventionalcommits.org/en/v1.0.0/#summary

By using conventional commits we can automate the releases with the classification of new feature, doc changes or bug fixes.

Refer to this video for more info -
https://www.youtube.com/watch?v=fcHJZ4pMzBs

Download husky checking linting of commit messages - 
https://www.youtube.com/watch?v=FKVjAz505cY

**Comment by hasnainmakada-99** [comment]
Hey @SahilSinghTomar thanks for informing me about the ways that we can automate, but you actually have to implement it in real and test it inside your fork

**Comment by SahilSinghTomar** [comment]
yeah

**Comment by SahilSinghTomar** [comment]
I will solve be able to solve this issue for next 2 weeks because of my college exams. So i m unassigning myself.
Sorry for the inconvenience caused. 
But looking forward to contribute after 2-3 weeks.

**Comment by hasnainmakada-99** [comment]
Everyone, This issue is up for grabs

**Comment by adesh1998** [comment]
could you help me understand the condition for a certain amount of commits after which the changelog should get updated?

**Comment by hasnainmakada-99** [comment]
@adesh1998 What is the actual thing for which you want the clearance like in which way I should make you understand this issue can you please address that

**Comment by hasnainmakada-99** [comment]
Hey @adesh1998 any updates on this issue ?

**Comment by hasnainmakada-99** [comment]
Closing this ISSUE

Reason: in Stale
