### ISSUE TITLE
Accessibility Issue over Link colors and background colors

### ISSUE THREAD

**Issue by at-the-vr** [hasnainmakada-99/Open-Source-with-Hasnain#213]
**Describe the bug**
 The contrast between foreground link colors and background colors don't meet WCAG 2 AA minimum contrast ratio thresholds

**To Reproduce**
1. Navigate to [Home Page](https://oswh.tech/#/pages/open-source-resources)
2. Check the links that are active in sidebar or provided inside the table
3. Using [Axe Dev Tools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en) from Chrome Extensions helps to find them a bit quicker

**Expected behavior**
According to WCAG guidelines, the links color can be altered such that for Light theme, the shade of green is darker (#485907 for example) and for dark Theme, the shade of Blue can be turned lighter (#6F9BE7 for example)

**Screenshots**
![image](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/assets/88548999/cee0ebc0-be8b-48c4-90b4-637b4e516714)

**Comment by hasnainmakada-99** [comment]
Hey @at-the-vr would you like to solve this issue?

**Comment by at-the-vr** [comment]
Yeah sure

**Comment by hasnainmakada-99** [comment]
Hey @at-the-vr I've assigned this issue to you
