### ISSUE TITLE
Add new resources in open source

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#28]
Add new resources in open sources for beginners to contribute to it and also get started with it

**Comment by KrishJ4856** [comment]
Hey @hasnainmakada-99 I saw the [open source resources.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/open-source-resources.md) file. 
I think there are a few more amazing resources that can be added to it including
1. [How to get started with Open Source by Web Dev Simplified](https://youtu.be/GbqSvJs-6W4)
2. [Complete Guide to Open Source - How to Contribute by freecodecamp ft eddie jaoude](https://youtu.be/yzeVMecydCE)
3. [Complete Git and GitHub Tutorial by Kunal Kushwaha](https://youtu.be/apGV9Kg7ics)
4. Eddie Jaoude's YouTube Channel
5. Kunal's My Experiences Playlist on YouTube
6. [First Contribution GitHub Repo](https://github.com/firstcontributions/first-contributions)
7. [GitHub Good First Issue Finder](https://finder.eddiehub.io/)

> I know they are a ton of resources but they are also among the best and from my view, the list would be lonely without them

What do you think about them?

**Comment by hasnainmakada-99** [comment]
You can contribute to the repo @KrishJ4856, I think it will be great

**Comment by KrishJ4856** [comment]
Raised a PR!

**Comment by Ajiboso-Adeola** [comment]
I would love to  contribute to  this

**Comment by hasnainmakada-99** [comment]
Here you go, @Ajiboso-Adeola

**Comment by hasnainmakada-99** [comment]
@Ajiboso-Adeola have you started working on this ?

**Comment by Ajiboso-Adeola** [comment]
Yes

**Comment by hasnainmakada-99** [comment]
Hey @Ajiboso-Adeola , Any updates on this one ?

**Comment by hasnainmakada-99** [comment]
Hello @Ajiboso-Adeola ?

**Comment by hasnainmakada-99** [comment]
Anybody else would like to solve this issue ?

**Comment by Rishav1707** [comment]
> Anybody else would like to solve this issue ?

Shall I work on this issue?

**Comment by hasnainmakada-99** [comment]
Yeah Sure @Rishav1707,
