### ISSUE TITLE
Add more resources in web development

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#29]
More resources should be added inside web development,

the directory structure is as follow,

[./pages/web-development-resources](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/web-development-resources.md)

**Comment by Arbtrage** [comment]
Hey @hasnainmakada-99 , I would love to work on this issue.

**Comment by hasnainmakada-99** [comment]
Here you go @Arbtrage
