### ISSUE TITLE
Add: Issue and pull request template

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#3]
Add issue template and pull request template so that whenever users raise a new issue or PR, they can specify what changes and issues are being made

To know more about what are issues and pull request templates, you can check out here

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by KlausMikhaelson** [comment]
Hey @hasnainmakada-99 would like to work on it, can you assign it to me?

**Comment by hasnainmakada-99** [comment]
Here you go @KlausMikhaelson

**Comment by KlausMikhaelson** [comment]
@hasnainmakada-99 can you please stay online for few more mins will create a pr as soon as possible just need one pr for the hacktoberfest   lol

**Comment by hasnainmakada-99** [comment]
Sorry @KlausMikhaelson hacktoberfest is now over. you can take your time to complete it

**Comment by KlausMikhaelson** [comment]
@hasnainmakada-99 uhhh 4 hrs are left like when it gets 1st nov in every time zone that it's gonna over I do have some prs but unfortunately they are all in other time zones, I don't need the swag I just need the badge just wanna try even if I don't get it doesn't matter but still just want to try

**Comment by hasnainmakada-99** [comment]
> @hasnainmakada-99 uhhh 4 hrs are left like when it gets 1st nov in every time zone that it's gonna over I do have some prs but unfortunately they are all in other time zones, I don't need the swag I just need the badge just wanna try even if I don't get it doesn't matter but still just want to try

Okay then go for it.. and make sure that you're still contributing to open source and not just for hacktoberfest @KlausMikhaelson

**Comment by hasnainmakada-99** [comment]
Hey @KlausMikhaelson, Have you started working on this issue

Here are your references,

PR Template reference : https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/.github/PULL_REQUEST_TEMPLATE.md

Issue Template reference : https://github.com/Dun-sin/smartsearch/tree/main/.github/ISSUE_TEMPLATE

**Comment by KlausMikhaelson** [comment]
Hey will create the pr before the end of the day !
Thank you !

**Comment by hasnainmakada-99** [comment]
> Hey will create the pr before the end of the day ! Thank you !

No worries

And raise a single PR, Referencing this issue @KlausMikhaelson

**Comment by hasnainmakada-99** [comment]
Hey @KlausMikhaelson, Are you still working on this one  ?

**Comment by hasnainmakada-99** [comment]
Hey @KlausMikhaelson are you working on this or should I assign this someone else
