### ISSUE TITLE
Add resources for Data Structures and Algorithms

### ISSUE THREAD

**Issue by ghost** [hasnainmakada-99/Open-Source-with-Hasnain#30]
## Add new resources in Data Structures. The directory structures should be as follows, 
./pages/data-structures-and-algorithms-resources

**Comment by sohel-79** [comment]
Adding few resources 
1) https://www.coursera.org/learn/algorithms-part1
2) https://www.coursera.org/learn/algorithms-part2
3) https://www.coursera.org/specializations/data-structures-algorithms
4) https://youtu.be/rZ41y93P2Qo - Kunal Kushwaha

**Comment by ghost** [comment]
Hey @sohel-79, please add the above links in the respective directory.

### directory structure (create a .md file inside the pages folder) 👇
./pages/data-structure-and-algorithms-resources

### Note: To know how to add resources refer to https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/devops-resources.md
