### ISSUE TITLE
Add new resources in machine learning 

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#31]
The directory structure to add resources is as follows

https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/machine-learning-resources.md

**Comment by hugosmoreira** [comment]
@hasnainmakada-99 Hello There, Add new resources like free tutorials and videos about Machine Learning? I was browsing and got curious about this repo I may can help with that. Thanks!

**Comment by hasnainmakada-99** [comment]
Yes @hugosmoreira , you can add resources if you wish to, for reference take this as an example of how to add resources

https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/devops-resources.md

**Comment by hugosmoreira** [comment]
That's nice thanks for the answer if you want you can assign this to me and I will make a machine learn resources using this as an example.

**Comment by hasnainmakada-99** [comment]
Okay then @hugosmoreira, I'm assigning this issue to you

**Comment by hasnainmakada-99** [comment]
hey @hugosmoreira, are you done working on this ?

**Comment by hugosmoreira** [comment]
@hasnainmakada-99 can I finish during the weekend? I got really busy at work this week

**Comment by hasnainmakada-99** [comment]
No problem, take your time

**Comment by hasnainmakada-99** [comment]
@hugosmoreira, any updates ?

**Comment by hugosmoreira** [comment]
@hasnainmakada-99 I apologize would you mind in unassigned to me? You said to take my time and still tag me all the time, I got part done but I wanted to do without pressure. Thank you

**Comment by hasnainmakada-99** [comment]
No problem @hugosmoreira, please go on, I just ask you because if this issue is stagnant for a long time, then the bot will close it automatically so in order to make it alive, I ask you

If you're still working on it then please continue, I have no objections

**Comment by hugosmoreira** [comment]
@hasnainmakada-99 please unassign I don't want to be tagged here anymore thank you

**Comment by vaibhavx42** [comment]
I would like to work on this can you assign this to me @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Here you go @vaibhavx42

**Comment by vaibhavx42** [comment]
@hasnainmakada-99 Should the resource be in tabular form as done in https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/devops-resources.md or it can be bulletin format?. The bulletin format is looking clean.

**Comment by hasnainmakada-99** [comment]
Yes @vaibhavx42 the resources should be in the same format as it is described in the devOps-resources.md

**Comment by vaibhavx42** [comment]
Submitted it as done in  devOps-resources.md can you check @hasnainmakada-99

**Comment by vaibhavx42** [comment]
@hasnainmakada-99 I've submitted pr for this issue
