### ISSUE TITLE
Fix images resolution in OpenSourceResources.md

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#39]
The thumbnail of resources should be 320 x 180, redesign the thumbnails again with canva and upload it here

the directory structure to open source resources file is as follows,

[./pages/opensource-resources.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/open-source-resources.md)

as for talking about the images, create a new folder inside the `pages` directory name `images` and paste the images over there itself

**Comment by mirazxmondal** [comment]
Can I work on this if no one has yet been assigned to the issue?

**Comment by hasnainmakada-99** [comment]
Ya sure, @miraz-mondal

**Comment by mirazxmondal** [comment]
Hey @hasnainmakada-99, I had few doubts first being all the files are in markdown and images are being some sort of CDNs, so do I have to resize all the images and now inside the pages directory I will create a new directory named images and there every images will be saved locally and then in markdown I will set specific path for each images or in ./pages/opensource-resources.md I will have to just resize the "GitHub Good First Issue Finder" thumbnail and raise a pull request? 
![OSW](https://user-images.githubusercontent.com/89645073/209991214-294f0561-896f-4567-ae88-4a69045353cd.png)

**Comment by hasnainmakada-99** [comment]
Yeah exactly @miraz-mondal you can do that too

**Comment by mirazxmondal** [comment]
Okay done, I have raised a PR. Please check it!
