### ISSUE TITLE
Add more content in Web Development and DevOps

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#4]
The directory structure to add more content is as follows

[./docs/pages](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/tree/main/docs/pages)

**Comment by ghost** [comment]
May I handle this issue?

**Comment by hasnainmakada-99** [comment]
Go for it @edson-sooraj

**Comment by hasnainmakada-99** [comment]
I'll review the pr by tomorrow, will that be okay @edson-sooraj. Got stuck in some college work

**Comment by ghost** [comment]
no probs :)
