### ISSUE TITLE
I would like to enhance the look of the README.md file.

### ISSUE THREAD

**Issue by alok-38** [hasnainmakada-99/Open-Source-with-Hasnain#49]
**Is your feature request related to a problem? Please describe.**
A I would like to enhance the look of the README.md file by adding some colorful borders between sections to make it more readable

**Comment by hasnainmakada-99** [comment]
You can proceed for that @alok-38

**Comment by hasnainmakada-99** [comment]
I am assigning this issue to you

**Comment by hasnainmakada-99** [comment]
For this issue, you have made changes inside the [Readme.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/README.md) file

**Comment by alok-38** [comment]
I'm a newbie  to opensource contributions. I will read the rules again and then start contributing once I fully understand.

**Comment by hasnainmakada-99** [comment]
> I'm a newbie  to opensource contributions. I will read the rules again and then start contributing once I fully understand.

Yup 😀

**Comment by hasnainmakada-99** [comment]
@alok-38 any updates on this one ?

**Comment by alok-38** [comment]
I'm really sorry.I totally forgot to unassign myself. Actually that's what I meant.

**Comment by hasnainmakada-99** [comment]
So should I close this issue ? @alok-38
