### ISSUE TITLE
Web development resource requires a major update 

### ISSUE THREAD

**Issue by alok-38** [hasnainmakada-99/Open-Source-with-Hasnain#51]
Could I please suggest some updates to the Web Development resource page?

I see that the list is not well structured. We can certainly do it better by structuring it well (In the order of increasing difficulties)

Also we need to point the visitors in the right direction.

Also how about improving the thumbnails? Say make it more responsive and interactive.

Please advice if I could work on the above?

**Comment by hasnainmakada-99** [comment]
Yes @alok-38, tell me when you're ready, you can work on this issue

**Comment by alok-38** [comment]
I'm ready to work on this issue.

**Comment by hasnainmakada-99** [comment]
Okay then I am assigning this issue to you

**Comment by hasnainmakada-99** [comment]
Hello @alok-38 , I've closed all the PR's which you raised because you've touched some sensitive files in which changes were not required, Create a new fork and start fresh again, And now only touch the files which I mention in the issue description

**Comment by hasnainmakada-99** [comment]
For this issue, you have to make changes only inside the [Web-development-resources.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/web-development-resources.md)

**Comment by alok-38** [comment]
Okay. I will do that.

**Comment by hasnainmakada-99** [comment]
@alok-38 any updates on this issue ?

**Comment by hasnainmakada-99** [comment]
@alok-38 ?
