### ISSUE TITLE
Add beginner to expert level resources in Android Development

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#55]
**Is your feature request related to a problem? Please describe.**
I would like to request the contributors that you have to add resources regarding android-development inside the [android-development.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/android-development-resources.md) file

While adding the resources, make sure to keep the thumbnail size 320w x 180h, and for the reference of how it is done, [check out here](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/devops-resources.md).

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
If any additional things will be there, then this issue will be edited

**Comment by vaibhavx42** [comment]
Is anyone working on this? If not I'd like to work on this.

**Comment by hasnainmakada-99** [comment]
Yes @vaibhavx42, I'm assigning it to you 😀

**Comment by hasnainmakada-99** [comment]
Hello @vaibhavx42 have you started working on this ?

**Comment by vaibhavx42** [comment]
Yes @hasnainmakada-99 I'm working on it and I'll finish it before this weekend .

**Comment by hasnainmakada-99** [comment]
Okay NP @vaibhavx42
