### ISSUE TITLE
Suggestion Regarding .github Folder

### ISSUE THREAD

**Issue by vaibhavx42** [hasnainmakada-99/Open-Source-with-Hasnain#56]
**Is your feature request related to a problem? Please describe.**
I was looking at the .github folder and noticed that there is no code of conduct and Changelog file in the project. 

**Describe the solution you'd like**
I can add a Code of conduct file and a Change log file. The logs file shows the version and the changes as your repository grows.

**Additional context**
A code of conduct is an important part of any open-source community and helps to establish a respectful and inclusive environment.

**Comment by hasnainmakada-99** [comment]
Yes @vaibhavx42, I would be happy to help you if you get stuck anywhere, please proceed to solve this issue, I'm assigning it to you 😀

**Comment by vaibhavx42** [comment]
@hasnainmakada-99 I have added the links to the relevant files in the README.md file. Please let me know if you have any preferences for the formatting or if you would like me to make any changes in this format.
![itiswhatitis](https://user-images.githubusercontent.com/110530263/211191940-de20395e-73c2-4923-81a9-d1a127560ce8.png)
