### ISSUE TITLE
Enhancement in Readme.md file of this project

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#59]
**Is your feature request related to a problem? Please describe.**
The contributor should make new enhancements in the main Readme.MD of this project

The path to the readme file: [../../Readme.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/README.md)

**Describe the solution you'd like**
**None**

**Describe alternatives you've considered**
**None**

**Additional context**
**Please create a fork and a new branch while making changes to the main readme.md file**

**Comment by imtiazpy** [comment]
What are the guidelines and standards for creating a comprehensive and effective Readme.md file, and what should be included in the file to make it most useful for users and contributors?

**Comment by imtiazpy** [comment]
Can you suggest some of the projects for ideas that should I follow ?

**Comment by hasnainmakada-99** [comment]
> What are the guidelines and standards for creating a comprehensive and effective Readme.md file, and what should be included in the file to make it most useful for users and contributors?

Hey @imtiazpy, I have gone through a great resource while I was creating this project, here's the link

https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

**Comment by hasnainmakada-99** [comment]
> Can you suggest some of the projects for ideas that should I follow ?

As for talking about projects, check out
Open source with pradumna by clicking the link below. It is a great project and it has helped me a lot

https://github.com/Pradumnasaraf/open-source-with-pradumna

**Comment by the-amazing-atharva** [comment]
@hasnainmakada-99 I am a beginner to open source , I would like to contribute README.md
Sending a PR in sometime!
