### ISSUE TITLE
Add support for both, Light and Dark theme for OSWH

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#66]
**Is your feature request related to a problem? Please describe.**
I would like to request the contributor that they should add a toggle button with which the user can switch to light and dark mode

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
Please mention this issue while raising the PR.

**Comment by yung-coder** [comment]
Hey @hasnainmakada-99 i would like to work on this ..

**Comment by hasnainmakada-99** [comment]
Great saksham, I'm assigning it you ☺️
