### ISSUE TITLE
Add more resources in Web Development 

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#72]
The directory structure to add resources is as follows: [../pages/web-development-resources.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/web-development-resources.md)

**Comment by Rishav1707** [comment]
Shall I?

**Comment by hasnainmakada-99** [comment]
Let's get you both assigned, but please make sure that you don't create merge conflicts, @Rishav1707 @ashutosh0022
