### ISSUE TITLE
Create a Dockerfile which buillds the docker image for this project

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#76]
**Is your feature request related to a problem? Please describe.**
Write a docker file which creates the docker image for this project and exposes the port at localhost:3000

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
For reference on how to build a docker image, please refer [here](https://www.stereolabs.com/docs/docker/creating-your-image/)

**Comment by TonyBhargav** [comment]
@hasnainmakada-99 , I'd like to work on this issue. Can you please assign me this. I'll start working on creating docker file.
Thank You

**Comment by hasnainmakada-99** [comment]
Yes you can go for it @TonyBhargav

**Comment by hasnainmakada-99** [comment]
Hello @TonyBhargav, Have you started working on this ?

**Comment by hasnainmakada-99** [comment]
@TonyBhargav ?

**Comment by TonyBhargav** [comment]
@hasnainmakada-99 Got busy with work
Tomorrow I will look into it once

**Comment by hasnainmakada-99** [comment]
No problem @TonyBhargav

**Comment by hasnainmakada-99** [comment]
@TonyBhargav, any updates?

**Comment by hasnainmakada-99** [comment]
Hello @Hunt092, Would you like to work on this issue?
