### ISSUE TITLE
New Header for OSWH

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#80]
The current header for OSWH looks like this ⬇️ 
![image](https://user-images.githubusercontent.com/82728823/214527784-313e441c-8256-4c09-8dbd-a78dde2fdc56.png)

- ###  **The contributor should make a new header for this project and the resolution of the header should be 1600 W x 450 H**. And don't forget to make it compatible with both light and dark mode

**Comment by Umayarz18** [comment]
Hey, curious about more info on this issue.  
- Does this need to be an image or would you like it to be an SVG? 
- Is there an original design file (figma, sketch) with this header design to reference?

Just asking to better understand what solution would work best. I'm hoping to tackle this issue after further guidance 😄

**Comment by hasnainmakada-99** [comment]
**Hey @Umayarz18, The image should be in a PNG or a SVG format. and second thing is you can take the existing header design for reference from the project and for designing I would prefer you to use canva for that because the current header was designed in that that's why.** 

**don't forget the dimensions: 1600 W x 450 H**

**if you statically need the asset, then contact me and I'll mail you**

**Comment by Umayarz18** [comment]
@hasnainmakada-99  I will be using SVG format in order to make it themeable to dark/light modes. I do not think that is possible with a PNG. Do you mind sending the Canva file or provide a reference on the typography font and font size you used when making the original asset?

**Comment by hasnainmakada-99** [comment]
Yes sure @Umayarz18, I'll send it here and should I assign this issue ?

**Comment by hasnainmakada-99** [comment]
Here is the project header image, it's in PNG format ⏬ 
![Project Header](https://user-images.githubusercontent.com/82728823/215001759-c58fd800-ea91-4142-b790-45448bb7e02c.png)

And here is the font details of the text being used inside the cover image ⬇️ 

**Font family: Acherus Militant Light**

**Font Size: 50-51**

**Font Style: Bold**
