### ISSUE TITLE
Adding License section in README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [hasnainmakada-99/Open-Source-with-Hasnain#85]
I would like to add the License section in the README for contributors to see easily!

**Comment by hasnainmakada-99** [comment]
I don't think that's necessary @the-amazing-atharva , because the contributors can easily see the licence from the right side navigation

![image](https://user-images.githubusercontent.com/82728823/215248953-073cdb7b-4a88-4bf1-9768-0119ee44518d.png)

**Comment by the-amazing-atharva** [comment]
Yeah actually its ok!
