### ISSUE TITLE
Add greeting.yaml workflow

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#9]
Whenever a new contributor raises a pull request or opens up an issue, they should be greeted and thanked for doing that.

To look at the reference of how the workflow looks like, Check out here

https://github.com/marketplace/actions/greet-contributors-action

**Comment by ghost** [comment]
I'll handle this.

**Comment by ghost** [comment]
My college work got in the way. I'll take care of this issue by Sunday.

**Comment by hasnainmakada-99** [comment]
> My college work got in the way. I'll take care of this issue by Sunday.

No worries @edson-sooraj , Take your time
