### ISSUE TITLE
Add new resources inside machine learning

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#90]
# The directory structure for ML file is as follows,

[./pages/machine-learning-resources.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/machine-learning-resources.md)

**Feel free to raise any questions related to this issue**

**Comment by Vishvsalvi** [comment]
Can I work on this issue?

**Comment by hasnainmakada-99** [comment]
Ya sure @Vishvsalvi

**Comment by alaminrifat** [comment]
I have made a pull request. Kindly review it.
