### ISSUE TITLE
Add: Search bar functionality to easily search content across the website

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#97]
**Is your feature request related to a problem? Please describe.**
### **I would like to request the contributor to add a search bar functionality which should easily make content accessible to the users, and the searching should be efficient enough to recognize certain keywords.**

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
You can refer to the official dosify docs from which this project is created for certain references

https://docsify.js.org/#/

**Comment by Frenziecodes** [comment]
Assign it to me sir .

**Comment by hasnainmakada-99** [comment]
Here you go @lewisushindi

**Comment by hasnainmakada-99** [comment]
Hey @lewisushindi , Any updates ?

**Comment by ghost** [comment]
heya @lewisushindi are you still working on this issue?

**Comment by junaidahamed800** [comment]
@hasnainmakada-99 Hi Can i contribute to this?

**Comment by hasnainmakada-99** [comment]
Sorry @junaidahamed800, This issue is currently been assigned to @lewisushindi. If this issue stays unsolved for a longer period of time, then I'll assign it to you

**Comment by junaidahamed800** [comment]
@hasnainmakada-99 i can resolve it this issue faster , can you confirm if @lewisushindi's progress till now?

**Comment by hasnainmakada-99** [comment]
Let's wait for @lewisushindi, It's not at all about who can solve the issue faster.

**Comment by Frenziecodes** [comment]
@hasnainmakada-99 am almost finishing the issue..sorry for the delay.

**Comment by ghost** [comment]
heya, @lewisushindi I am happy that you are working on it. Take your time. If you face any issues do let us know

**Comment by hasnainmakada-99** [comment]
No worries @lewisushindi, Take your time

**Comment by hasnainmakada-99** [comment]
This issue is now open @edsodz, @lewisushindi unassigned himself

**Comment by yung-coder** [comment]
@hasnainmakada-99 i will look into it..

**Comment by hasnainmakada-99** [comment]
@yung-coder
