### ISSUE TITLE
Typo in Android Development Section

### ISSUE THREAD

**Issue by Arbtrage** [hasnainmakada-99/Open-Source-with-Hasnain#99]
**Describe the bug**
There is a typo error in the Android Development section, point number 8.

**To Reproduce**
Steps to reproduce the behavior 

**Expected behavior**
Instead of "8. Now **thay** you've learned let's build it Project 1" it should be "8. Now **that** you've learned let's build it Project 1"

**Screenshots**
![image](https://user-images.githubusercontent.com/100552235/216721582-d86842a2-fceb-41f6-ac47-fb023ba5a9f2.png)

**Additional context**

**Comment by Arbtrage** [comment]
@hasnainmakada-99 can you assign me this issue ?

**Comment by hasnainmakada-99** [comment]
Here you go, @Arbtrage
